apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html  # Katalog, w którym Nginx szuka plików do wyświetlania
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: test-dynamic-pvc 

          
