apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dynamic-pvc
spec:
  storageClassName: "nfs-storage" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 